server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 9000

spring:
  datasource:
    username: root
    password: haohao123
    url: jdbc:mysql://127.0.0.1:3306/des_simu?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  activiti:
    check-process-definitions: true #自动检查、部署流程定义文件
    database-schema-update: true #自动更新数据库结构
    #流程定义文件存放目录
    process-definition-location-prefix: classpath:/processes/
    #process-definition-location-suffixes: #流程文件格式

#日志的相关配置
logging:
  level:
    root: info

#activiti7 历史表的创建（解决已存在的bug）
spring.activiti.history-level: full
spring.activiti.db-history-used: true

# spring-activiti （没啥用）
# 自动部署验证设置:true-开启（默认）、false-关闭
spring.activiti.check-process-definitions: false

#文件配置
file:
  #federation的bpmn文件路径
  federationBPMNPath: /Users/america/Desktop/Activiti-develop/des_simulation/src/main/resources/FederationBPMN
  #FileController将数据上传到的路径，注意要有一个'/'
  filepath: /Users/america/Desktop/Activiti-develop/des_simulation/src/main/resources/FederationBPMN/
  #将上传上来的文件解析到的文件夹
  showbpmnpath: /Users/america/Desktop/Activiti-develop/des_simulation/src/main/resources/processes/
  #bpmn文件加载的路径+/
  processespath: /Users/america/Desktop/Activiti-develop/des_simulation/src/main/resources/processes/
  #bpmn加载路径的文件夹
  processesfilefolder: /Users/america/Desktop/Activiti-develop/des_simulation/src/main/resources/processes
